### ISSUE TITLE
Add proper return error to denied connections

### ISSUE THREAD

**Issue by xSmurf** [subgraph/roflcoptor#1]
Instead of just closing the connection, we should return a proper 51x error to the client.

**Comment by david415** [comment]
Technically this feature is incorrect... right? Line protocol clients are only expecting to see error codes from the server in response from their client queries. But I guess it doesn't matter since we are closing the connection anyway.

Currently we do send 5xx error codes to the client when a particular command is denied via the filtration policy.

**Comment by david415** [comment]
https://github.com/subgraph/roflcoptor/commit/b269a4cd2c13baf1bbcab3c18693404e05abd771
