### ISSUE TITLE
Make sure ADD_ONION cannot bind to any of the control ports

### ISSUE THREAD

**Issue by xSmurf** [subgraph/roflcoptor#17]
For policies that allow ADD_ONION commands, we need to make sure that it cannot bind to any of the control ports (that is neither the original control port, nor any of the filter ports).

**Comment by david415** [comment]
fixed https://github.com/subgraph/roflcoptor/commit/4dbb28159af576784b8415726c0b3f8204b2085f

**Comment by david415** [comment]
this issue is most likely not fixed... now that i'm actually writing unit tests i should have this mess sorted soon.

**Comment by david415** [comment]
i wrote unit tests for this feature; here
https://github.com/subgraph/roflcoptor/blob/888e6c00a83b0710326f8961c59e6e6304cdaf70/session_test.go#L435-L463

i've fixed some bugs with it... but maybe it's still not good enough?

**Comment by david415** [comment]
shouldAllowOnion now has full test coverage. i've since then fixed several bugs with it and added more tests.

i'm pretty happy with it now but i wonder if i've overlooked some detail that could allow a client program talking to our filter daemon to create an onion service which connects to a control port?
