### ISSUE TITLE
Write filter for onioncircuits

### ISSUE THREAD

**Issue by xSmurf** [subgraph/roflcoptor#3]

**Comment by david415** [comment]
i believe onioncircuits requires it's connection to the control port to be via unix domain socket.
therefore this issue depends on first resolving -> https://github.com/subgraph/roflcoptor/issues/9

**Comment by david415** [comment]
i patched onioncircuits here:
https://github.com/david415/onioncircuits/tree/add_control_port_env.0

and filed this ticket with the tails dev team here:
https://labs.riseup.net/code/issues/11402

i tested my patched onioncircuits with my dev branch of roflcoptor that can
listen on a unix domian socket (if it's specified in the config):
https://github.com/david415/roflcoptor/commits/1.add_unix_domain_socket.2

In watch mode I was able to see all the chatting onioncircuits did to what it thought was the tor control port... At this point I'm not sure how to filter this traffic without a regex because many of the server responses begin with a circuit ID. I'll have to think about this some more.

**Comment by david415** [comment]
i landed the unix domain socket + multi-listener feature. we just need to figure out how best to filter onioncircuits. the responses start with the circuit id and we should allow this is the filter policy but so far our filter policies only work my either exact string match, prefix match... whereas we perhaps want a way to say allow all server responses.

**Comment by david415** [comment]
the author of onioncircuits has added the requested feature addition of user specified control port allowing for a unix domain socket file. the latest onioncircuits testing package in debian may well contain the new feature.

**Comment by leif** [comment]
I have a filter for onioncircuits in the branch at https://github.com/subgraph/roflcoptor/pull/45 but it currently applies to all python3.5 apps because the per-app-socket functionality is broken (in both roflcoptor and oz, apparently).

**Comment by david415** [comment]
per-app-socket functionality or policy listeners are now working correctly in roflcoptor. furthermore here's my pull-request for an onioncircuits oz profile: https://github.com/subgraph/oz/pull/73

my modification of leif's onioncircuits roflcoptor policy file specifies a unix socket listener for the roflcoptor onioncircuits policy listener:
https://github.com/david415/roflcoptor/blob/add_onioncircuits_policy.0/filters/onioncircuits.json

this socket file /var/run/roflcoptor/onioncircuits.socket is used by the oz profile for onioncircuits in the above pull request.

**Comment by david415** [comment]
this feature was merged!
