### ISSUE TITLE
remove dependency on procsnitch

### ISSUE THREAD

**Issue by adrelanos** [subgraph/roflcoptor#56]
Is the procsnitch dependency important or could it please be removed?

**Comment by david415** [comment]
no we should not remove procsnitchd as a dependency because it's a privilege separation daemon which allows roflcoptor run as an unprivileged user. i could see an argument for making a build tag to optionally build roflcoptor without procsnitchd so that all the listeners have a configured policy attached to them; does that sound like a helpful alternative?

**Comment by adrelanos** [comment]
Yes.

**Comment by david415** [comment]
ok we decided to remove procsnitchd as a dependency since we don't really need it to select a filter policy because we can use the listener as the only means of selecting a policy. Each listener has a policy assigned to it.

**Comment by david415** [comment]
work in progress -> https://github.com/david415/roflcoptor/tree/56.remove_procsnitch.0

**Comment by david415** [comment]
i've tested roflcoptor without procsnitchd and it works...
but i need others to test it as well to make sure!

@dma 
https://github.com/subgraph/roflcoptor/pull/60
